scenarios:
# 10 clients, 4 scenarios, see Excel file
  scenario_1:
    total_share: 1
    valid_share: 0.2
    test_share: 0.4
    num_reruns: 5
    max_num_epochs: 60
    learning_rate: 0.001
    early_stopping_patience: 2
    early_stopping_monitor: "loss"
    clients:
      client_1:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_2:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_3:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_4:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_5:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_6:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_7:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_8:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_9:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
      client_10:
        subtotal_no_pitting_share: 0.1
        subtotal_pitting_share: 0.1
  scenario_2:
    total_share: 1
    valid_share: 0.2
    test_share: 0.4
    num_reruns: 5
    max_num_epochs: 60
    learning_rate: 0.001
    early_stopping_patience: 2
    early_stopping_monitor: "loss"
    clients:
      client_1:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.16
      client_2:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.16
      client_3:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.16
      client_4:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.16
      client_5:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.16
      client_6:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.04
      client_7:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.04
      client_8:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.04
      client_9:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.04
      client_10:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.04
  scenario_3:
    total_share: 1
    valid_share: 0.2
    test_share: 0.4
    num_reruns: 5
    max_num_epochs: 60
    learning_rate: 0.001
    early_stopping_patience: 2
    early_stopping_monitor: "loss"
    clients:
      client_1:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.16
      client_2:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.04
      client_3:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.16
      client_4:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.04
      client_5:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.16
      client_6:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.04
      client_7:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.16
      client_8:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.04
      client_9:
        subtotal_no_pitting_share: 0.04
        subtotal_pitting_share: 0.16
      client_10:
        subtotal_no_pitting_share: 0.16
        subtotal_pitting_share: 0.04
  scenario_4:
    total_share: 1
    valid_share: 0.2
    test_share: 0.4
    num_reruns: 5
    max_num_epochs: 60
    learning_rate: 0.001
    early_stopping_patience: 2
    early_stopping_monitor: "loss"
    clients:
      client_1:
        subtotal_no_pitting_share: 0.0597
        subtotal_pitting_share: 0.2388
      client_2:
        subtotal_no_pitting_share: 0.2388
        subtotal_pitting_share: 0.0597
      client_3:
        subtotal_no_pitting_share: 0.0597
        subtotal_pitting_share: 0.2388
      client_4:
        subtotal_no_pitting_share: 0.2388
        subtotal_pitting_share: 0.0597
      client_5:
        subtotal_no_pitting_share: 0.0597
        subtotal_pitting_share: 0.2388
      client_6:
        subtotal_no_pitting_share: 0.0597
        subtotal_pitting_share: 0.0149
      client_7:
        subtotal_no_pitting_share: 0.0149
        subtotal_pitting_share: 0.0597
      client_8:
        subtotal_no_pitting_share: 0.0597
        subtotal_pitting_share: 0.0149
      client_9:
        subtotal_no_pitting_share: 0.0149
        subtotal_pitting_share: 0.0597
      client_10:
        subtotal_no_pitting_share: 0.0597
        subtotal_pitting_share: 0.0149
# # 2 clients, 4 scenarios, see Excel file
  # scenario_1:
  #   total_share: 0.1
  #   valid_share: 0.2
  #   test_share: 0.4
  #   num_reruns: 5
  #   max_num_epochs: 60
  #   learning_rate: 0.001
  #   early_stopping_patience: 2
  #   early_stopping_monitor: "loss"
  #   clients:
  #     client_1:
  #       subtotal_no_pitting_share: 0.5
  #       subtotal_pitting_share: 0.5
  #     client_2:
  #       subtotal_no_pitting_share: 0.5
  #       subtotal_pitting_share: 0.5
#   scenario_2:
#     total_share: 1
#     valid_share: 0.2
#     test_share: 0.4
#     num_reruns: 5
#     max_num_epochs: 60
#     learning_rate: 0.001
#     early_stopping_patience: 2
#     early_stopping_monitor: "loss"
#     clients:
#       client_1:
#         subtotal_no_pitting_share: 0.8
#         subtotal_pitting_share: 0.8
#       client_2:
#         subtotal_no_pitting_share: 0.2
#         subtotal_pitting_share: 0.2
#   scenario_3:
#     total_share: 1
#     valid_share: 0.2
#     test_share: 0.4
#     num_reruns: 5
#     max_num_epochs: 60
#     learning_rate: 0.001
#     early_stopping_patience: 2
#     early_stopping_monitor: "loss"
#     clients:
#       client_1:
#         subtotal_no_pitting_share: 0.8
#         subtotal_pitting_share: 0.2
#       client_2:
#         subtotal_no_pitting_share: 0.2
#         subtotal_pitting_share: 0.8
#   scenario_4:
#     total_share: 1
#     valid_share: 0.2
#     test_share: 0.4
#     num_reruns: 5
#     max_num_epochs: 60
#     learning_rate: 0.001
#     early_stopping_patience: 2
#     early_stopping_monitor: "loss"
#     clients:
#       client_1:
#         subtotal_no_pitting_share: 0.235
#         subtotal_pitting_share: 0.941
#       client_2:
#         subtotal_no_pitting_share: 0.235
#         subtotal_pitting_share: 0.059
# # 5 clients, 4 scenarios, see Excel file
  # scenario_1:
  #   total_share: 1
  #   valid_share: 0.2
  #   test_share: 0.4
  #   num_reruns: 5
  #   max_num_epochs: 60
  #   learning_rate: 0.001
  #   early_stopping_patience: 2
  #   early_stopping_monitor: "loss"
  #   clients:
  #     client_1:
  #       subtotal_no_pitting_share: 0.2
  #       subtotal_pitting_share: 0.2
  #     client_2:
  #       subtotal_no_pitting_share: 0.2
  #       subtotal_pitting_share: 0.2
  #     client_3:
  #       subtotal_no_pitting_share: 0.2
  #       subtotal_pitting_share: 0.2
  #     client_4:
  #       subtotal_no_pitting_share: 0.2
  #       subtotal_pitting_share: 0.2
  #     client_5:
  #       subtotal_no_pitting_share: 0.2
  #       subtotal_pitting_share: 0.2
  # scenario_2:
  #   total_share: 1
  #   valid_share: 0.2
  #   test_share: 0.4
  #   num_reruns: 5
  #   max_num_epochs: 60
  #   learning_rate: 0.001
  #   early_stopping_patience: 2
  #   early_stopping_monitor: "loss"
  #   clients:
  #     client_1:
  #       subtotal_no_pitting_share: 0.3636
  #       subtotal_pitting_share: 0.3636
  #     client_2:
  #       subtotal_no_pitting_share: 0.3636
  #       subtotal_pitting_share: 0.3636
  #     client_3:
  #       subtotal_no_pitting_share: 0.0909
  #       subtotal_pitting_share: 0.0909
  #     client_4:
  #       subtotal_no_pitting_share: 0.0909
  #       subtotal_pitting_share: 0.0909
  #     client_5:
  #       subtotal_no_pitting_share: 0.0909
  #       subtotal_pitting_share: 0.0909
  # scenario_3:
  #   total_share: 1
  #   valid_share: 0.2
  #   test_share: 0.4
  #   num_reruns: 5
  #   max_num_epochs: 60
  #   learning_rate: 0.001
  #   early_stopping_patience: 2
  #   early_stopping_monitor: "loss"
  #   clients:
  #     client_1:
  #       subtotal_no_pitting_share: 0.071
  #       subtotal_pitting_share: 0.286
  #     client_2:
  #       subtotal_no_pitting_share: 0.286
  #       subtotal_pitting_share: 0.071
  #     client_3:
  #       subtotal_no_pitting_share: 0.071
  #       subtotal_pitting_share: 0.286
  #     client_4:
  #       subtotal_no_pitting_share: 0.286
  #       subtotal_pitting_share: 0.071
  #     client_5:
  #       subtotal_no_pitting_share: 0.071
  #       subtotal_pitting_share: 0.286
  # scenario_4:
  #   total_share: 1
  #   valid_share: 0.2
  #   test_share: 0.4
  #   num_reruns: 5
  #   max_num_epochs: 60
  #   learning_rate: 0.001
  #   early_stopping_patience: 2
  #   early_stopping_monitor: "loss"
  #   clients:
  #     client_1:
  #       subtotal_no_pitting_share: 0.138
  #       subtotal_pitting_share: 0.552
  #     client_2:
  #       subtotal_no_pitting_share: 0.552
  #       subtotal_pitting_share: 0.138
  #     client_3:
  #       subtotal_no_pitting_share: 0.034
  #       subtotal_pitting_share: 0.138
  #     client_4:
  #       subtotal_no_pitting_share: 0.138
  #       subtotal_pitting_share: 0.034
  #     client_5:
  #       subtotal_no_pitting_share: 0.034
  #       subtotal_pitting_share: 0.138
